# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/x00ad/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/asus/x00ad/proprietary
endif
