# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/wileyfox/crackling/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/wileyfox/crackling/proprietary
endif
